version: "2"

services:

  hub:
    image: "selenium/hub"
    ports:
      - "4444:4444"
    networks:
      - "selenium-grid"

  chrome:
    image: "selenium/node-chrome"
    environment:
      - "HUB_HOST=hub"
      - "HUB_PORT=4444"
    ports:
      - "9001:5900"
    depends_on:
      - "hub"
    networks:
      - "selenium-grid"
    
  test-all:
    build:
      context: "robotframework"
    command: "-v remote_url:hub -v emailAddress:${emailAddress} -v password:${password} --outputdir /out /tests/testcases/"
    volumes:
      - "./robotframework/tests:/tests:ro"
      - "./results/all:/out:rw"
    depends_on:
      - "hub"
      - "chrome"
    networks:
      - "selenium-grid"

networks:
  selenium-grid:
